from . import help
from . import start
from . import echo
from . import anketa
from . import ishga_anketa
from . import uz_menuHandlers
from . import rus_menuHandlers
from . import вакансыя
from . import анкета